master:
  image: redis:3
  container_name: master
  hostname: master
 # environment:
  #  - affinity:service!=slave
  ports:
  - 6379:6379
  - 16061:16061
slave:
  image: redis:3
  command: redis-server --slaveof master 6379
  links:
    - master:master
sentinel:
  build: sentinel
  hostname: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
  #  - affinity:service!=master
  #  - affinity:service!=slave
  # - affinity:service!=sentinel
  links:
    - master:master
    - slave
