master:
  build: ./master
  container_name: master
  hostname: master
  volumes:
  - './master/redis.conf:/usr/local/etc/redis/redis.conf'
  ports:
  - 6379:6379
slave1:
  build: ./slave1
  container_name: slave1
  hostname: slave1
  environment:
    REDIS_PORT: '6371'
  links:
  - master
  ports:
  - 6379:6371
  - 16061:16061
slave2:
  build: ./slave2
  container_name: slave2
  environment:
    REDIS_PORT: '6372'
  hostname: slave2
  links:
  - master
  ports:
  - 6379:6372
  - 16062:16062



