master:
  build: ./master
  container_name: master
  hostname: master
  volumes:
  - './master/redis.conf:/usr/local/etc/redis/redis.conf'
  ports:
  - 6379:6379
slave1:
  build: ./slave
  container_name: slave1
  hostname: slave1
  environment:
    REDIS_PORT: 6371
  links:
  - master
  volumes:
  - './slave/redis.conf:/usr/local/etc/redis/redis.conf'
  ports:
  - 6371:6371
  - 16061:16061
slave2:
  build: ./slave
  container_name: slave2
  hostname: slave2
  environment:
    REDIS_PORT: 6372
  volumes:
  - './slave/redis.conf:/usr/local/etc/redis/redis.conf'
  links:
  - master
  ports:
  - 6373:6373
  - 16062:16062
slave3:
  build: ./slave
  container_name: slave3
  hostname: slave3
  environment:
    REDIS_PORT: 6373
  volumes:
  - './slave/redis.conf:/usr/local/etc/redis/redis.conf'
  links:
  - master
  ports:
  - 6373:6373
  - 16063:16063



