master:
  build: ./master
  container_name: master
  hostname: master
  volumes:
  - './master/redis.conf:/usr/local/etc/redis/redis.conf'
  ports:
  - 6379:6379
slave1:
  build: ./slave1
  container_name: slave1
  hostname: slave1
  links:
  - master
  ports:
  - 6371:6371
  - 16061:16061
slave2:
  build: ./slave2
  container_name: slave2
  hostname: slave2
  links:
  - master
  ports:
  - 6372:6372
  - 16062:16062



